name: Script Management

on:
  push:
    branches:
      - main

jobs:
  manage-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-

      - name: Install Dependencies
        run: |
          npm install
          npm install -g prettier eslint eslint-plugin-prettier eslint-config-prettier

      - name: Lint Scripts
        run: |
          npx eslint scripts/*.js

      - name: Auto Format Scripts
        run: |
          npx prettier --write scripts/*

      - name: Extract Metadata
        run: |
          node extract-metadata.js

      - name: Generate Page
        run: |
          node generate-page.js

      - name: Commit Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add metadata.json page/index.html page/style.css page/script.js
          git commit -m "Update metadata and page" || exit 0
          git push origin main

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./page
          destination_dir: ./