name: Script Management

on:
  push:
    branches:
      - main

jobs:
  manage-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 缓存 Node 模块
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-

      - name: 安装依赖
        run: |
          npm install

      - name: 构建
        env:
          GITHUB_RAW_URL: "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/"
        run: |
          npm run build

      - name: 提交更改
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .*
          git commit -m "更新元信息和页面" || exit 0
          git push origin main

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./page
          destination_dir: ./