name: Script Management

on:
  push:
    branches:
      - main

jobs:
  manage-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Auto Format Scripts
        run: |
          # 使用 Prettier 格式化脚本
          npx prettier --write scripts/*

      - name: Extract Metadata
        run: |
          # 从脚本中提取元信息并生成 metadata.json
          node extract-metadata.js

      - name: Generate Page
        run: |
          # 根据 metadata.json 生成管理页面
          node generate-page.js

      - name: Commit Changes
        run: |
          # 提交并推送更改
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add metadata.json page/index.html page/style.css page/script.js
          git commit -m "Update metadata and page" || exit 0
          git push origin main

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./page
          destination_dir: ./  # 如果需要覆盖根目录，可以省略或修改